[package]
name = "text-edit"
version = "0.0.0"
repository = "https://github.com/rust-lang/rust-analyzer"
description = "Representation of a `TextEdit` for rust-analyzer."

authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
doctest = false

[dependencies]
itertools.workspace = true
text-size.workspace = true

[lints]
workspace = true