[package]
name = "paths"
version = "0.0.0"
description = "Path wrappers for absolute and relative paths."

authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
doctest = false

[dependencies]
camino.workspace = true
serde = { workspace = true, optional = true }

[features]
serde1 = ["camino/serde1", "dep:serde"]

[lints]
workspace = true
