[package]
name = "limit"
version = "0.0.0"
description = "A struct to enforce limits."

authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[features]
tracking = []

[lints]
workspace = true
